### ISSUE TITLE
FOW continues to draw after "Design" is selected

### ISSUE THREAD

**Issue by metaky** [josephwegner/hexamagon#13]
Will see if I can find what triggers it, but now all the cells I'm filling new are coming in with color AND FOW gradation.

**Comment by metaky** [comment]
It's possible that I "filled" FOW on blank spaces and did not see a pattern on it, then when I filled with color it came out as FOW. However, this also was applying to spaces that were colored, not previously FOW, and then when I changed color it filled them in with the new color with FOW active.

So I'd split this into 2 issues - create a FOW indicator for blank tiles (white), and then fix the actual bug too.

**Comment by josephwegner** [comment]
Unable to repro - will close, and we can reopen if it happens again.
